github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/yespornplease-downloader",
  "https://serp.co/products/yespornplease-downloader/reviews/",
  "https://extensions.serp.co/yespornplease-downloader",
  "https://browserextensions.io/yespornplease-downloader"
]
